### ISSUE TITLE
Upgrade Retrofit up to 2.+ version

### ISSUE THREAD

**Issue by cosic** [LiveTyping/u2020-mvp#16]

**Comment by cosic** [comment]
https://speakerdeck.com/jakewharton/simple-http-with-retrofit-2-droidcon-nyc-2015

**Comment by cosic** [comment]
https://github.com/square/retrofit/blob/master/CHANGELOG.md

**Comment by kboyarshinov** [comment]
@cosic lgtm except some issues I left comments about.

**Comment by kboyarshinov** [comment]
:+1: lgtm
