### ISSUE TITLE
Leak

### ISSUE THREAD

**Issue by IgorGanapolsky** [LiveTyping/u2020-mvp#22]
Hello,
your app leaks GalleryActivity, according to LeakCanary:
![leak](https://cloud.githubusercontent.com/assets/201209/12682040/9206c57e-c67f-11e5-8b73-fb5d5232df90.png)

Steps to reproduce:
1) launch the app
2) hit back button to exit the app

**Comment by cosic** [comment]
@IgorGanapolsky Thanks a lot for issue. Seems I've fixed it. Could you check the issue?

**Comment by cosic** [comment]
@IgorGanapolsky Fixed issue is in a [am/#22_leak](https://github.com/LiveTyping/u2020-mvp/tree/am/%2322_leak) branch.

**Comment by IgorGanapolsky** [comment]
@cosic  I have tested your branch and confirmed that the issue's been fixed.  Keep up the good work.  @changetip $1

**Comment by changetip** [comment]
Hi @cosic, @IgorGanapolsky sent you a tip worth 2,717 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/937698)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by cosic** [comment]
@IgorGanapolsky Thanks for donating! =)
