### ISSUE TITLE
Enhancement in GalleryDatabase.java

### ISSUE THREAD

**Issue by IgorGanapolsky** [LiveTyping/u2020-mvp#25]
Hi,
I am looking at your code in GalleryDatabase, and I see this comment:

> ```
>     // Warning: Gross shit follows! Where you at Java 8?
> ```

`
galleryService.listGallery(section, Sort.VIRAL, 1)
                .filter(Results.isSuccess())
                .map(new GalleryToImageList())
                .flatMap(new Func1<List<Image>, Observable<? extends Image>>() {
                    @Override
                    public Observable<? extends Image> call(List<Image> iterable) {
                        return Observable.from(iterable);
                    }
                })
                .filter(new Func1<Image, Boolean>() {
                    @Override public Boolean call(Image image) {
                        return !image.is_album; // No albums.
                    }
                })
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(galleryRequest);
`

I have thought about how to enhance this code block with Java 8, but cannot figure it out.  I mean, Java 8 Streams are nice, but they won't provide any improvement to the code you've already written.

Thoughts?
Igor

**Comment by cosic** [comment]
@IgorGanapolsky I think you are right. Do you offer to remove this comment from code?

**Comment by IgorGanapolsky** [comment]
I think so, since Java 8 Streams will do nothing to improve it anyway.
