### ISSUE TITLE
Hi, TestGalleryComponent having problem, I was using AS 1.1.0 to run it

### ISSUE THREAD

**Issue by shawnthye** [LiveTyping/u2020-mvp#3]
Dagger_GalleryActivityTest$TestGalleryComponent

F:\Git\Samples\u2020-mvp\app\src\androidTest\java\ru\ltst\u2020mvp\tests\GalleryActivityTest.java
Error:(89, 5) error: ru.ltst.u2020mvp.tests.GalleryActivityTest.TestGalleryComponent (unscoped) cannot depend on scoped components:
@ru.ltst.u2020mvp.ui.ApplicationScope ru.ltst.u2020mvp.U2020Component
@ru.ltst.u2020mvp.ui.gallery.GalleryScope ru.ltst.u2020mvp.ui.gallery.GalleryComponent

**Comment by shawnthye** [comment]
I tried both Junit and Android Instrumentation also havent the same issue...do you have any idea?

**Comment by kboyarshinov** [comment]
@shawnthye Thanks! I know about that. This is related to Dagger 2 snapshot update with scricter rules about component dependencies. Let's keep this issue as a reminder to fix it.

**Comment by shawnthye** [comment]
wow...thanks for the quick reply...
