### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by IgorGanapolsky** [LiveTyping/u2020-mvp#4]
Hi,
What is the purpose of `ActivityHierarchyServer NONE` here: https://github.com/IgorGanapolsky/u2020-mvp/blob/master/app/src/main/java/ru/ltst/u2020mvp/ui/ActivityHierarchyServer.java#L14

It seems similar to the `Empty` inner class below it.

**Comment by kboyarshinov** [comment]
Hi Igor,

In previous versions it was provided as release `ActivivityHierarchyServer`, now `Empty` is provided with extra overridings. So I guess it can be safely removed.
