### ISSUE TITLE
Possible unused code (presenter exposed by GalleryComponent)

### ISSUE THREAD

**Issue by fpezzato** [LiveTyping/u2020-mvp#5]
Hi!
 could you please verify if in the class `GalleryComponent.java`  this line `GalleryActivity.Presenter presenter()`  is  necessary? 
Direct like: https://github.com/LiveTyping/u2020-mvp/blob/master/app/src/main/java/ru/ltst/u2020mvp/ui/gallery/GalleryComponent.java#L14

In can compile/execute the app without the line, in fact the presenter in injected in the `GalleryActivity`. 

Ps. I'm studying/testing Dagger2 in these days, so I'm not sure if this is a real issue or not! :wink:

**Comment by kboyarshinov** [comment]
Hi! Yep, that can be removed safely. Presenter is created by constructor injection therefore it is not required to be listed in component interface.
PR is welcome. Thank you!

**Comment by fpezzato** [comment]
Thanks for the response! ;)
Just opened the PR (https://github.com/LiveTyping/u2020-mvp/pull/7)

..and thanks for this repo! :100:
